version: '2'
services:
  sequelize-sortable-datastore:
    image: busybox
    volumes:
      - ./tmp/db:/var/lib/postgresql/data:rw
    container_name: sequelize-sortable-datastore
  sequelize-sortable-pg:
    build:
      context: ./database
      dockerfile: ./Dockerfile
    image: postgres-ja:9.6.1
    environment:
      POSTGRES_USER: robin
      POSTGRES_PASSWORD: password
    ports:
      - "127.0.0.1:5442:5432"
    container_name: sequelize-sortable-pg
    volumes_from:
      - sequelize-sortable-datastore
